import streamlit as st

# -----------------------------
# App Layout
# -----------------------------
st.set_page_config(page_title="Reinsurance Claim Decision System", layout="wide")

st.title("📑 Reinsurance Claim Decision System (Demo UI)")

# Sidebar menu
menu = ["Submit Claim", "Policies & Rules", "Past Claims", "Reports"]
choice = st.sidebar.radio("Navigate", menu)

# -----------------------------
# Submit Claim Page
# -----------------------------
if choice == "Submit Claim":
    st.subheader("📝 Submit a New Claim")

    claimant_name = st.text_input("Claimant Name")
    claimant_email = st.text_input("Claimant Email")
    claim_text = st.text_area("Claim Description")

    uploaded_docs = st.file_uploader("Upload Claim Documents", type=["pdf", "docx", "txt"], accept_multiple_files=True)

    if st.button("Submit for Evaluation"):
        st.success("✅ Claim submitted successfully (UI demo).")
        st.info("👉 In the real app, this will be checked against rules & policies.")

# -----------------------------
# Policies & Rules Page
# -----------------------------
elif choice == "Policies & Rules":
    st.subheader("📚 Company Policies & Rules")
    st.write("This section will display internal rules, policies, and laws relevant to decision making.")
    st.info("UI demo only — policies will be loaded from backend later.")

# -----------------------------
# Past Claims Page
# -----------------------------
elif choice == "Past Claims":
    st.subheader("📂 Past Claims Records")
    st.table([
        {"Claim ID": "C001", "Claimant": "John Doe", "Decision": "Accepted"},
        {"Claim ID": "C002", "Claimant": "Jane Smith", "Decision": "Rejected"},
    ])
    st.info("UI demo only — data will be fetched from database later.")

# -----------------------------
# Reports Page
# -----------------------------
elif choice == "Reports":
    st.subheader("📊 Generated Reports")
    st.write("Here you will see decision reports with references to policies/laws.")
    st.info("UI demo only — reports will be generated by LLM + rules engine later.")
